### PR TITLE
feat: overwritten colors in the loader

### LINKED ISSUE #285: Loader is always the same color
I wanted to use the `Loader` in a `Button` to indicate a long running action in the background. The issue is that the Loader is always dark (in light mode) so if I put it on a strong Button it is not really visible.

It would be good if the Loader color could be changed or even better, if it worked similarly to icons that does not need the color to be specified.

The code is something like this:
```svelte
        <Button variant="strong" onclick={() => createToken()}>
            Create token
            {#if createDisabled}
                <Loader/>
            {:else}
                <ArrowRight/>
            {/if}
        </Button>
```

### PR DESCRIPTION
**Pull request by hlavkat**
resolve #285

### CODE REVIEW

**Review by agazso — COMMENTED** [review]
With this change you can change the global `--loader-color` which is not what I wanted. It is also possible to pass an extra `style` parameter which makes it possible, but it is a bit cumbersome.

It would be better if I could specify with a prop which version to use.
For example a prop could be `color: 'high' | 'low'`, defaulting to `high` and it would display the current version (which uses `--colors-ultra-high`).
But if I passed `low` then the border color would be `--colors-ultra-low` only for that instance of the loader.

**Comment by vojtechsimetka** [comment]
By the way, CSS variables can be easily overwritten by passing them into the svelte component - see https://sveltebyexample.com/css-custom-properties/

**Review by agazso — APPROVED** [review]
Excellent!

**Comment by agazso** [comment]
> By the way, CSS variables can be easily overwritten by passing them into the svelte component - see https://sveltebyexample.com/css-custom-properties/

Interesting, I did not know about this and looks useful. I think this would be a nice addition to a lot of components for customization (for example to change a custom button background color).

Still for the loader I think the simplest solution is the one that is currently implemented.

**Pull request merged**
