### PR TITLE
fix: date input default style

### LINKED ISSUE #209: Date input has default style
The date input has a default (system) style and that means it may appear with mono font for the date and a system provided calendar icon, which may look off, see the attached example.

It would be better if it looked like the normal text input with a button and a calendar icon from carbon icons.

Screenshot-20240528164742-646x334

### PR DESCRIPTION
**Pull request by hlavkat**
resolve #209

### CODE REVIEW

**Review by agazso — COMMENTED** [review]
Does not work for me on Chrome and Firefox.

**Comment by hlavkat** [comment]
> > I don't really like it, but it's the only way I found to hide the icon in firefox @agazso
> 
> My issue is that nothing happens when I click on the date icon. Tested in Chrome and Firefox.


Yes, clicking on the added button will not show anything, because the separate calendar has not yet been implemented.
I just wanted to hide the default icon

**Comment by agazso** [comment]
> Yes, clicking on the added button will not show anything, because the separate calendar has not yet been implemented. I just wanted to hide the default icon

I see but this breaks existing functionality, because you can no longer use a date picker, whereas previously at least there was a date picker with the default style. I think it is better to not have features than having half-working ones. In this case I would consider not supporting date input at all.

**Comment by hlavkat** [comment]
> I see but this breaks existing functionality, because you can no longer use a date picker, whereas previously at least there was a date picker with the default style. I think it is better to not have features than having half-working ones. In this case I would consider not supporting date input at all.

I understand, well in that case I delete the label for now right?

**Review by vojtechsimetka — APPROVED** [review]

**Pull request merged**
